# Generated by Django 4.1 on 2022-09-06 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ClassName", models.CharField(max_length=100)),
                ("ClassYear", models.CharField(max_length=100)),
                ("ClassSem", models.CharField(max_length=100)),
                ("ClassCapacity", models.IntegerField()),
                (
                    "ClassCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StudentCode", models.CharField(max_length=10)),
                ("StudentName", models.CharField(max_length=100)),
                ("StudentYear", models.IntegerField(blank=True, null=True)),
                ("StudentSem", models.IntegerField(blank=True, null=True)),
                (
                    "StudentUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Enrolled", models.BooleanField()),
                (
                    "EnrollClass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.class"
                    ),
                ),
                (
                    "EnrollUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
